services:
  - type: web
    name: flashfuelbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: USDT_TRON_ADDRESS
        sync: false
      - key: ETH_ADDRESS
        sync: false
      - key: BTC_ADDRESS
        sync: false
      - key: GPT_API_KEY
        sync: false
      - key: NFT_ACCESS_GROUP
        sync: false
